#!/bin/bash
# Nginx Admin Installer
# Website: www.nginxcp.com
#
# Copyright (C) NGINXCP.COM.
# 
cd /usr/local/src
wget -c  https://github.com/MohamedMohsenX2/nginxcp/archive/master.zip
unzip master.zip
cd /usr/local/src/nginxcp-master/mod_rpaf-0.8.4
#cd mod_rpaf-0.8.4/
/usr/local/apache/bin/apxs -i -c -n mod_rpaf.so mod_rpaf.c
/usr/local/cpanel/bin/apache_conf_distiller --update

/scripts/rebuildhttpdconf

if grep "rpaf.conf"  /usr/local/apache/conf/httpd.conf ; then
/scripts/rebuildippool > /dev/null 2>&1
LIST=$(/scripts/ipusage | awk '{print $1}'|while read ip; do echo -ne "${ip} "; done)
cat > /usr/local/apache/conf/includes/rpaf.conf << EOF
LoadModule rpaf_module modules/mod_rpaf.so
#Mod_rpaf settings
RPAFenable On
RPAFproxy_ips 127.0.0.1 $LIST
RPAFsethostname On
RPAFheader X-Real-IP
EOF
else
/scripts/rebuildippool 
LIST=$(/scripts/ipusage | awk '{print $1}'|while read ip; do echo -ne "${ip} "; done)
cat > /usr/local/apache/conf/includes/rpaf.conf << EOF
LoadModule rpaf_module  modules/mod_rpaf.so
#Mod_rpaf settings
RPAFenable On
RPAFproxy_ips 127.0.0.1 $LIST
RPAFsethostname On
RPAFheader X-Real-IP
EOF
echo "Include \"/usr/local/apache/conf/includes/rpaf.conf\""  >> /usr/local/apache/conf/httpd.conf
fi

service httpd restart
